export { type TypicalElementProps } from '~typical/editor/types/TypicalEditor.types'
export { default as TypicalEditor } from '~typical/editor/components/Typical.vue'
export { Typical } from '~typical/editor/Typical'
export { type ITypicalElement } from '~typical/editor/TypicalElement'
export { type TypicalStyle } from '~typical/editor/TypicalEditorStyleProvider'